<?php
namespace Database\Seeders;
use App\Models\{Measurement,MeasurementSet,MeasurementValue,Trial,TrialStageRecord,TrialTemplate,WorkflowStage,WorkflowTemplate}; use Illuminate\Database\Seeder;
class WorkflowSeeder extends Seeder{public function run():void{
$defs=[['YLD','Rendement','kg/m²','number','sum','up','Production',30,7.8,6.9],['BRIX','°Brix (sucre)','°Bx','number','mean','up','Qualité',25,13.2,12.1],['PMF','Poids moyen / fruit','g','number','mean','up','Production',15,1250,1180],['NBF','Nombre de fruits / plant','fruits','number','mean','up','Production',10,4.2,4.5],['FRM','Fermeté','/10','scale','mean','up','Qualité',10,7.5,7],['CONS','Conservation','jours','number','mean','up','Qualité',10,18,15]];
$set=MeasurementSet::updateOrCreate(['id'=>1],['name'=>['fr'=>'Profil melon standard'],'description'=>['fr'=>'Mesures de production et de qualité.']]);foreach($defs as$i=>[$code,$name,$unit,$type,$agg,$dir,$cat,$weight]){$m=Measurement::updateOrCreate(['code'=>$code],['name'=>['fr'=>$name],'unit'=>$unit,'data_type'=>$type,'aggregation'=>$agg,'direction'=>$dir,'category'=>$cat,'description'=>['fr'=>'Mesure standard configurable.'],'active'=>true]);$set->measurements()->syncWithoutDetaching([$m->id=>['default_weight'=>$weight,'sort_order'=>$i]]);}
$workflow=WorkflowTemplate::updateOrCreate(['id'=>1],['name'=>['fr'=>'Cycle variétal standard'],'description'=>['fr'=>'Cycle complet semis → clôture.'],'is_default'=>true,'allow_trial_overrides'=>true,'is_archived'=>false]);$mids=$set->measurements()->pluck('measurements.id')->all();$stages=[['creation','Création',['fields'=>[['key'=>'objective','name'=>['fr'=>'Objectif de l’essai'],'type'=>'textarea','required'=>true]],'required_to_advance'=>true,'completion_roles'=>['admin','manager']]],['semis','Semis',['fields'=>[['key'=>'date','name'=>['fr'=>'Date'],'type'=>'date','required'=>true],['key'=>'sowing_origin','name'=>['fr'=>'Origine du semis'],'type'=>'text','required'=>true]],'required_to_advance'=>true,'completion_roles'=>['admin','manager','technician']]],['greffage','Greffage',['fields'=>[['key'=>'date','name'=>['fr'=>'Date'],'type'=>'date','required'=>true]],'completion_roles'=>['admin','manager','technician']]],['transplantation','Transplantation',['fields'=>[['key'=>'date','name'=>['fr'=>'Date'],'type'=>'date','required'=>true],['key'=>'density','name'=>['fr'=>'Densité'],'type'=>'decimal','required'=>false]],'required_to_advance'=>true,'completion_roles'=>['admin','manager','technician']]],['evaluation','Évaluation',['measurement_ids'=>$mids,'required_to_advance'=>true,'completion_roles'=>['admin','manager','agronomist']]],['resultat','Résultat',['measurement_ids'=>$mids,'required_to_advance'=>true,'completion_roles'=>['admin','manager','agronomist']]],['decision','Décision',['required_to_advance'=>true,'completion_roles'=>['admin']]],['cloture','Clôture',['completion_roles'=>['admin','manager']]]];foreach($stages as$i=>[$key,$name,$config])WorkflowStage::updateOrCreate(['workflow_template_id'=>$workflow->id,'key'=>$key],['name'=>['fr'=>$name],'sort_order'=>$i,'config'=>$config]);$workflow->load('stages');$set->load('measurements');$template=TrialTemplate::updateOrCreate(['id'=>1],['name'=>['fr'=>'Essai melon standard'],'workflow_template_id'=>$workflow->id,'measurement_set_id'=>$set->id,'config'=>['allow_stage_overrides'=>true],'is_archived'=>false]);
$ws=$workflow->stages->map(fn($s)=>['key'=>$s->key,'name'=>$s->name,'sort_order'=>$s->sort_order,'config'=>$s->config??[]])->values()->all();$ms=$set->measurements->map(fn($m)=>['id'=>$m->id,'code'=>$m->code,'name'=>$m->name,'unit'=>$m->unit,'data_type'=>$m->data_type,'aggregation'=>$m->aggregation,'direction'=>$m->direction,'weight'=>(float)$m->pivot->default_weight])->values()->all();
foreach(Trial::all()as$trial){$trial->update(['trial_template_id'=>$template->id,'workflow_template_id'=>$workflow->id,'measurement_set_id'=>$set->id,'workflow_snapshot'=>$ws,'measurement_snapshot'=>$ms]);$current=$workflow->stages->firstWhere('key',$trial->current_stage)?->sort_order??0;foreach($workflow->stages as$stage){$record=TrialStageRecord::updateOrCreate(['trial_id'=>$trial->id,'workflow_stage_id'=>$stage->id],['stage_key'=>$stage->key,'stage_name'=>$stage->name,'sort_order'=>$stage->sort_order,'config_snapshot'=>$stage->config,'status'=>$stage->sort_order===$current?'active':($stage->sort_order<$current?'completed':'pending'),'started_at'=>$stage->sort_order<=$current?now():null,'completed_at'=>$stage->sort_order<$current?now():null,'data'=>[]]);if(in_array($stage->key,['evaluation','resultat'],true))foreach($defs as[$code,,,,,,,,$trialValue,$controlValue]){$m=Measurement::where('code',$code)->first();foreach([['trial',$trial->variety,$trialValue],['control',$trial->controls[0]??'Témoin',$controlValue]]as[$type,$label,$value])MeasurementValue::updateOrCreate(['trial_id'=>$trial->id,'stage_record_id'=>$record->id,'measurement_id'=>$m->id,'subject_type'=>$type,'subject_label'=>$label],['value'=>$value]);}}}}
}
