<?php
namespace Tests\Feature;

use App\Domain\Metadata\MetadataService;
use App\Models\{FieldDefinition, Supplier, User, Variety};
use Database\Seeders\FieldDefinitionSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/** SPEC §3.1: metadata-driven fields — entity option sources, uniqueness, slug, and record CRUD. */
class MetadataFieldsTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();
        $this->seed(FieldDefinitionSeeder::class);
    }

    private function user(): User
    {
        return User::factory()->create(['role' => 'manager', 'email_verified_at' => now()]);
    }

    public function test_referentiel_record_can_be_updated_and_deleted(): void
    {
        $user = $this->user();
        $supplier = Supplier::create(['name' => 'Acme', 'code' => 'AC1', 'custom_data' => []]);

        $this->actingAs($user)->put("/referentiels/fournisseurs/{$supplier->id}", ['name' => 'Acme Corp', 'code' => 'AC1'])->assertRedirect();
        $this->assertSame('Acme Corp', $supplier->fresh()->name);

        $this->actingAs($user)->delete("/referentiels/fournisseurs/{$supplier->id}")->assertRedirect();
        $this->assertModelMissing($supplier);
    }

    public function test_unique_custom_field_blocks_duplicates(): void
    {
        FieldDefinition::create(['model_type' => 'supplier', 'key' => 'vat', 'label' => 'TVA', 'type' => 'text', 'is_unique' => true]);
        $user = $this->user();

        $this->actingAs($user)->post('/referentiels/fournisseurs', ['name' => 'A', 'vat' => 'FR123'])->assertRedirect();
        $this->actingAs($user)->post('/referentiels/fournisseurs', ['name' => 'B', 'vat' => 'FR123'])->assertSessionHasErrors('vat');
        $this->assertSame(1, Supplier::whereRaw("custom_data->>'vat' = 'FR123'")->count());
    }

    public function test_unique_system_field_blocks_duplicates(): void
    {
        FieldDefinition::where('model_type', 'supplier')->where('key', 'code')->update(['is_unique' => true]);
        $user = $this->user();

        $this->actingAs($user)->post('/referentiels/fournisseurs', ['name' => 'A', 'code' => 'DUP'])->assertRedirect();
        $this->actingAs($user)->post('/referentiels/fournisseurs', ['name' => 'B', 'code' => 'DUP'])->assertSessionHasErrors('code');
    }

    public function test_entity_sourced_multiselect_validates_existence(): void
    {
        FieldDefinition::create(['model_type' => 'variety', 'key' => 'suppliers', 'label' => 'Fournisseurs', 'type' => 'multiselect', 'settings' => ['option_source' => 'entity', 'reference_model' => 'supplier']]);
        $supplier = Supplier::create(['name' => 'S', 'custom_data' => []]);
        $user = $this->user();

        // Non-existent id is rejected.
        $this->actingAs($user)->post('/referentiels/varietes', ['name' => 'V1', 'suppliers' => [99999]])->assertSessionHasErrors('suppliers.0');
        // Valid id is accepted and stored as an array.
        $this->actingAs($user)->post('/referentiels/varietes', ['name' => 'V2', 'suppliers' => [$supplier->id]])->assertSessionHasNoErrors();
        $this->assertSame([$supplier->id], Variety::where('name', 'V2')->first()->custom_data['suppliers']);
    }

    public function test_slug_is_autogenerated_from_source_field(): void
    {
        FieldDefinition::create(['model_type' => 'supplier', 'key' => 'handle', 'label' => 'Slug', 'type' => 'text', 'settings' => ['slug_from' => 'name']]);
        $user = $this->user();

        $this->actingAs($user)->post('/referentiels/fournisseurs', ['name' => 'Green Fields Ltd'])->assertRedirect();
        $this->assertSame('green-fields-ltd', Supplier::where('name', 'Green Fields Ltd')->first()->custom_data['handle']);
    }

    public function test_legacy_reference_labels_do_not_break_referential_display(): void
    {
        $field = FieldDefinition::create([
            'model_type' => 'variety',
            'key' => 'suppliers',
            'label' => 'Fournisseurs',
            'type' => 'multiselect',
            'settings' => ['option_source' => 'entity', 'reference_model' => 'supplier'],
        ]);
        $variety = Variety::create([
            'name' => 'Legacy variety',
            'custom_data' => ['suppliers' => ['Syngenta', 'Clause']],
        ]);

        $display = MetadataService::displayMap(collect([$variety]), collect([$field]));

        $this->assertSame('Syngenta, Clause', $display[$variety->id]['suppliers']);
    }
}
