<?php
namespace Tests\Feature;
use App\Models\{Measurement,MeasurementSet,Trial,TrialTemplate,User,WorkflowStage,WorkflowTemplate,Workspace};
use Illuminate\Foundation\Testing\RefreshDatabase; use Tests\TestCase;
class TrialWorkflowRuntimeTest extends TestCase{use RefreshDatabase;
 private function setupDomain(User $admin):array{$workspace=Workspace::create(['name'=>'P3','created_by'=>$admin->id]);$m=Measurement::create(['name'=>['fr'=>'Rendement'],'code'=>'YLD','unit'=>'kg','data_type'=>'number','aggregation'=>'mean','direction'=>'up']);$set=MeasurementSet::create(['name'=>['fr'=>'Profil']]);$set->measurements()->attach($m->id,['default_weight'=>100,'sort_order'=>0]);$workflow=WorkflowTemplate::create(['name'=>['fr'=>'Cycle'],'is_default'=>true,'allow_trial_overrides'=>true]);$stage=WorkflowStage::create(['workflow_template_id'=>$workflow->id,'key'=>'evaluation','name'=>['fr'=>'Évaluation'],'sort_order'=>0,'config'=>['required_to_advance'=>true,'completion_roles'=>['admin'],'measurement_ids'=>[$m->id],'fields'=>[['key'=>'date','name'=>['fr'=>'Date'],'type'=>'date','required'=>true]]]]);WorkflowStage::create(['workflow_template_id'=>$workflow->id,'key'=>'cloture','name'=>['fr'=>'Clôture'],'sort_order'=>1,'config'=>[]]);$template=TrialTemplate::create(['name'=>['fr'=>'Essai'],'workflow_template_id'=>$workflow->id,'measurement_set_id'=>$set->id,'config'=>[]]);return compact('workspace','m','stage','template');}
 public function test_admin_creates_trial_from_template_and_advances_required_stage():void{$admin=User::factory()->create(['role'=>'admin','email_verified_at'=>now()]);$d=$this->setupDomain($admin);$this->actingAs($admin)->post('/trials',['code'=>'P30001','trial_template_id'=>$d['template']->id,'workspace_id'=>$d['workspace']->id,'variety'=>'V1','culture'=>'Melon','controls'=>['T1']])->assertRedirect();$trial=Trial::where('code','P30001')->firstOrFail();$this->assertNotNull($trial->workflow_snapshot);$record=$trial->stageRecords()->where('stage_key','evaluation')->firstOrFail();$this->actingAs($admin)->put("/trials/{$trial->id}/stages/{$record->id}",['fields'=>['date'=>'2026-07-18'],'measurements'=>[['measurement_id'=>$d['m']->id,'subject_type'=>'trial','subject_label'=>'V1','value'=>8.2],['measurement_id'=>$d['m']->id,'subject_type'=>'control','subject_label'=>'T1','value'=>7.1]]])->assertRedirect();$this->actingAs($admin)->post("/trials/{$trial->id}/stages/{$record->id}/advance")->assertRedirect();$this->assertSame('cloture',$trial->fresh()->current_stage);$this->assertDatabaseHas('measurement_values',['trial_id'=>$trial->id,'measurement_id'=>$d['m']->id,'subject_type'=>'trial']);}
 public function test_required_stage_cannot_advance_without_data():void{$admin=User::factory()->create(['role'=>'admin','email_verified_at'=>now()]);$d=$this->setupDomain($admin);$this->actingAs($admin)->post('/trials',['code'=>'P30002','trial_template_id'=>$d['template']->id,'workspace_id'=>$d['workspace']->id,'variety'=>'V2','culture'=>'Melon']);$trial=Trial::where('code','P30002')->firstOrFail();$record=$trial->stageRecords()->where('stage_key','evaluation')->firstOrFail();$this->actingAs($admin)->post("/trials/{$trial->id}/stages/{$record->id}/advance")->assertSessionHasErrors('stage');}
}
