<?php
namespace App\Http\Controllers;
use App\Domain\Metadata\Referentiels;
use App\Models\{Measurement,MeasurementSet,Trial,TrialTemplate,WorkflowStage,WorkflowTemplate};
use Illuminate\Http\{RedirectResponse,Request};
use Illuminate\Validation\Rule;
use Inertia\{Inertia,Response};

class WorkflowConfigurationController extends Controller
{
    private const TYPES=['number','scale','boolean','text']; private const AGGREGATIONS=['mean','sum','min','max','last']; private const DIRECTIONS=['up','down','neutral'];
    /** Stage input fields reuse the same rich type set as the metadata form builder (SPEC §3.1). */
    private const FIELD_TYPES=['text','textarea','number','integer','decimal','email','url','tel','select','multiselect','reference','boolean','date','datetime','color','rating','icon','media'];
    public function index(): Response{$referenceModels=collect(Referentiels::MAP)->map(fn($cfg)=>['model_type'=>$cfg['model']::MODEL_TYPE,'label'=>$cfg['label']])->values();return Inertia::render('Configuration/Workflow',['measurements'=>Measurement::orderBy('category')->orderBy('code')->get(),'sets'=>MeasurementSet::with('measurements')->orderBy('id')->get(),'workflows'=>WorkflowTemplate::with('stages')->orderBy('is_archived')->orderByDesc('is_default')->get(),'trialTemplates'=>TrialTemplate::with(['workflow:id,name','measurementSet:id,name'])->orderBy('is_archived')->get(),'options'=>['types'=>self::TYPES,'aggregations'=>self::AGGREGATIONS,'directions'=>self::DIRECTIONS],'fieldTypes'=>collect(self::FIELD_TYPES)->map(fn($t)=>['value'=>$t,'label'=>$t]),'referenceModels'=>$referenceModels]);}
    public function storeMeasurement(Request $r):RedirectResponse{Measurement::create($this->measurementData($r));return back()->with('success','Mesure ajoutée.');}
    public function updateMeasurement(Request $r,Measurement $measurement):RedirectResponse{$measurement->update($this->measurementData($r,$measurement));return back()->with('success','Mesure mise à jour.');}
    private function measurementData(Request $r,?Measurement $m=null):array{$d=$r->validate(['name'=>'required|string|max:100','code'=>['required','regex:/^[A-Z][A-Z0-9_]*$/',Rule::unique('measurements')->ignore($m)],'unit'=>'nullable|string|max:30','data_type'=>['required',Rule::in(self::TYPES)],'aggregation'=>['required',Rule::in(self::AGGREGATIONS)],'direction'=>['required',Rule::in(self::DIRECTIONS)],'category'=>'nullable|string|max:80','description'=>'nullable|string|max:500','active'=>'boolean']);return [...$d,'name'=>['fr'=>$d['name']],'description'=>($d['description']??null)?['fr'=>$d['description']]:null];}
    public function storeSet(Request $r):RedirectResponse{$set=MeasurementSet::create($this->setData($r));$this->syncSet($set,$r);return back()->with('success','Profil ajouté.');}
    public function updateSet(Request $r,MeasurementSet $measurementSet):RedirectResponse{$measurementSet->update($this->setData($r));$this->syncSet($measurementSet,$r);return back()->with('success','Profil mis à jour.');}
    private function setData(Request $r):array{$d=$r->validate(['name'=>'required|string|max:100','description'=>'nullable|string|max:500','items'=>'array','items.*.measurement_id'=>'required|exists:measurements,id','items.*.default_weight'=>'required|numeric|min:0|max:100']);return ['name'=>['fr'=>$d['name']],'description'=>($d['description']??null)?['fr'=>$d['description']]:null];}
    private function syncSet(MeasurementSet $set,Request $r):void{$sync=[];foreach($r->input('items',[])as$i=>$item)$sync[$item['measurement_id']]=['default_weight'=>$item['default_weight'],'sort_order'=>$i];$set->measurements()->sync($sync);}
    public function storeWorkflow(Request $r):RedirectResponse{$d=$this->workflowData($r);WorkflowTemplate::create($d);return back()->with('success','Workflow ajouté.');}
    public function updateWorkflow(Request $r,WorkflowTemplate $workflowTemplate):RedirectResponse{$workflowTemplate->update($this->workflowData($r));return back()->with('success','Workflow mis à jour.');}
    private function workflowData(Request $r):array{$d=$r->validate(['name'=>'required|string|max:100','description'=>'nullable|string|max:500','allow_trial_overrides'=>'boolean']);return ['name'=>['fr'=>$d['name']],'description'=>($d['description']??null)?['fr'=>$d['description']]:null,'allow_trial_overrides'=>$d['allow_trial_overrides']];}
    public function duplicateWorkflow(WorkflowTemplate $workflowTemplate):RedirectResponse{$copy=$workflowTemplate->replicate(['is_default']);$copy->name=['fr'=>($workflowTemplate->name['fr']??'Workflow').' (copie)'];$copy->is_default=false;$copy->save();foreach($workflowTemplate->stages as $stage){$new=$stage->replicate();$new->workflow_template_id=$copy->id;$new->save();}return back()->with('success','Workflow dupliqué.');}
    public function archiveWorkflow(WorkflowTemplate $workflowTemplate):RedirectResponse{abort_if($workflowTemplate->is_default,422,'Le workflow par défaut ne peut pas être archivé.');$workflowTemplate->update(['is_archived'=>!$workflowTemplate->is_archived]);return back()->with('success','Statut du workflow mis à jour.');}
    public function storeStage(Request $r,WorkflowTemplate $workflowTemplate):RedirectResponse{$d=$this->stageData($r,$workflowTemplate);$d['sort_order']=(int)$workflowTemplate->stages()->max('sort_order')+1;$workflowTemplate->stages()->create($d);return back()->with('success','Étape ajoutée.');}
    public function updateStage(Request $r,WorkflowStage $workflowStage):RedirectResponse{$workflowStage->update($this->stageData($r,$workflowStage->workflow_template_id,$workflowStage));return back()->with('success','Étape mise à jour.');}
    private function stageData(Request $r,$workflow,?WorkflowStage $stage=null):array{$wid=is_object($workflow)?$workflow->id:$workflow;$d=$r->validate(['name'=>'required|string|max:100','key'=>['required','regex:/^[a-z][a-z0-9_]*$/',Rule::unique('workflow_stages')->where('workflow_template_id',$wid)->ignore($stage)],'required_to_advance'=>'boolean','completion_roles'=>'array','completion_roles.*'=>Rule::in(['admin','manager','agronomist','technician']),'measurement_ids'=>'array','measurement_ids.*'=>'exists:measurements,id','fields'=>'array','fields.*.key'=>'required|string','fields.*.name'=>'required|array','fields.*.type'=>['required',Rule::in(self::FIELD_TYPES)],'fields.*.required'=>'boolean','fields.*.options'=>'nullable|array','fields.*.settings'=>'nullable|array']);return ['name'=>['fr'=>$d['name']],'key'=>$d['key'],'config'=>['required_to_advance'=>$d['required_to_advance'],'completion_roles'=>$d['completion_roles']??[],'measurement_ids'=>$d['measurement_ids']??[],'fields'=>array_map(fn($x)=>['key'=>$x['key'],'name'=>$x['name'],'type'=>$x['type'],'required'=>$x['required']??false,'options'=>$x['options']??null,'settings'=>$x['settings']??null],$d['fields']??[])]];}
    public function reorder(Request $r,WorkflowTemplate $workflowTemplate):RedirectResponse{$d=$r->validate(['stage_ids'=>'required|array','stage_ids.*'=>'integer']);abort_unless($workflowTemplate->stages()->whereIn('id',$d['stage_ids'])->count()===count($d['stage_ids']),422);foreach($d['stage_ids']as$i=>$id)$workflowTemplate->stages()->whereKey($id)->update(['sort_order'=>$i]);return back()->with('success','Ordre enregistré.');}
    public function destroyStage(WorkflowStage $workflowStage):RedirectResponse{abort_if(\App\Models\TrialStageRecord::where('workflow_stage_id',$workflowStage->id)->exists(),422,'Étape déjà utilisée par un essai.');$workflowStage->delete();return back()->with('success','Étape supprimée.');}
    public function storeTrialTemplate(Request $r):RedirectResponse{TrialTemplate::create($this->trialTemplateData($r));return back()->with('success','Modèle d’essai créé.');}
    public function updateTrialTemplate(Request $r,TrialTemplate $trialTemplate):RedirectResponse{abort_if(Trial::where('trial_template_id',$trialTemplate->id)->exists(),422,'Dupliquez ce modèle : il est déjà utilisé.');$trialTemplate->update($this->trialTemplateData($r));return back()->with('success','Modèle d’essai mis à jour.');}
    private function trialTemplateData(Request $r):array{$d=$r->validate(['name'=>'required|string|max:100','workflow_template_id'=>'required|exists:workflow_templates,id','measurement_set_id'=>'required|exists:measurement_sets,id']);return ['name'=>['fr'=>$d['name']],'workflow_template_id'=>$d['workflow_template_id'],'measurement_set_id'=>$d['measurement_set_id'],'config'=>['allow_stage_overrides'=>true]];}
    public function duplicateTrialTemplate(TrialTemplate $trialTemplate):RedirectResponse{$copy=$trialTemplate->replicate(['is_archived']);$copy->name=['fr'=>($trialTemplate->name['fr']??'Modèle').' (copie)'];$copy->is_archived=false;$copy->save();return back()->with('success','Modèle d’essai dupliqué.');}
    public function archiveTrialTemplate(TrialTemplate $trialTemplate):RedirectResponse{$trialTemplate->update(['is_archived'=>!$trialTemplate->is_archived]);return back()->with('success','Statut du modèle mis à jour.');}
}
